cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: admin@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Admin
      password: $2b$12$y75Izx/BBRhjS.wmvc54XeOuioS8tZxKieE0X1GoEWaewSUpTYRU2
    loctong:
      email: loctong@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Loc Tong
      password: $2b$12$y75Izx/BBRhjS.wmvc54XeOuioS8tZxKieE0X1GoEWaewSUpTYRU2
pre-authorized:
  emails:
  - melsby@gmail.com
